platform :ios, '8.0'
target 'app_ios' do
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
pod 'SDWebImage', '~>3.8'
pod 'Reachability', '~> 3.2'
pod 'NullSafe', '~> 1.2.2'
pod 'IQKeyboardManager'
pod 'pop', '~> 1.0'
pod 'Bugly'
pod 'BlocksKit', '~> 2.2.5'
pod 'TTTAttributedLabel'
end
